code --install-extension anseki.vscode-color
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension cssho.vscode-svgviewer
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.code-runner
code --install-extension GitHub.remotehub
code --install-extension GitHub.vscode-pull-request-github
code --install-extension golang.go
code --install-extension googlecloudtools.cloudcode
code --install-extension GraphQL.vscode-graphql
code --install-extension GraphQL.vscode-graphql-execution
code --install-extension GraphQL.vscode-graphql-syntax
code --install-extension hashicorp.terraform
code --install-extension jasonnutter.search-node-modules
code --install-extension kamikillerto.vscode-colorize
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension mindaro-dev.file-downloader
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode.atom-keybindings
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.remote-repositories
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension Pivotal.vscode-spring-boot
code --install-extension planbcoding.vscode-react-refactor
code --install-extension redhat.fabric8-analytics
code --install-extension redhat.java
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension shengchen.vscode-checkstyle
code --install-extension sleistner.vscode-fileutils
code --install-extension sohibe.java-generate-setters-getters
code --install-extension SonarSource.sonarlint-vscode
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscjava.vscode-spring-boot-dashboard
code --install-extension waderyan.nodejs-extension-pack
code --install-extension xabikos.JavaScriptSnippets